### ISSUE TITLE
React Landing Page Clone

### ISSUE THREAD

**Issue by pratingo** [pratingo/react-landing-page-clone#2]
Implement landing page with React and [`emotion`](https://emotion.sh/docs/introduction).

Rebuild it in React (looking at the code as little as possible).

## TODO

- [x] Choose a landing page from [Landingfolio](https://www.landingfolio.com/)
- [ ] Copy all elements of the landing page
- [x] Style the elements

## Stretch TODOs

- [x] Copy animations and videos
- [ ] Copy interactive parts of the website
- [x] Right after [creating your first (empty) Git commit](https://learn.upleveled.io/courses/btcmp-l-webfs-gen-0/modules/101-cheatsheet-command-line/#4-create-and-push-an-initial-commit), create a new branch. Use this branch to [open a pull request on GitHub](https://learn.upleveled.io/courses/btcmp-l-webfs-gen-0/modules/103-cheatsheet-git-github/#opening-pull-requests)

## Acceptance Criteria

- [ ] Preflight runs through without errors in your project
  - [ ] Link in your GitHub repo's About section: Netlify deployed website
- [ ] Link to original landing page in comment below
- [ ] Link to CodeSandbox in comment below
- [ ] [Drone bot](https://learn.upleveled.io/courses/btcmp-l-webfs-gen-0/modules/100-cheatsheet-tasks/#upleveled-drone) has been tagged and responded with a passing message
- [ ] Correct GitHub commit message format (see [Writing Commit Messages](https://learn.upleveled.io/courses/btcmp-l-webfs-gen-0/modules/103-cheatsheet-git-github/#writing-commit-messages))
